SELECT A.PRODUCT_CODE, A.PRICE*SUM(B.SALES_AMOUNT) AS SALES
FROM PRODUCT AS A
    INNER JOIN OFFLINE_SALE AS B
    ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE  -- GROUP BY는 그룹을 지어줄 뿐 연산이 안되므로 칼럼을 뽑을 때 SUM을 붙여야 함
ORDER BY SALES DESC, A.PRODUCT_CODE ASC